version: '3.3'

services:
  scrumvoting_database:
    container_name: scrumvoting_database
    image: mysql:8.0
    env_file:
      - .env.local
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: scrumvoting_database
      MYSQL_USER: scrumvoting
      MYSQL_PASSWORD: scrumvoting
    ports:
      - '4307:3306'
    volumes:
      - ./.docker/scrumvoting/mysql:/var/lib/mysql
  scrumvoting_app:
    container_name: scrumvoting_app
    env_file:
      - .env.local
    build:
      context: ./.docker/scrumvoting
      args:
        COUNTRY: ${COUNTRY}
        STATE: ${STATE}
        CITY: ${CITY}
        ORGANIZATION: ${ORGANIZATION}
        ORG_UNIT: ${ORG_UNIT}
        COMMON_NAME: ${COMMON_NAME}
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/scrumvoting
      - ssl-certs:/etc/ssl/certs
    depends_on:
      - scrumvoting_database
  scrumvoting_database_nginx:
    container_name: scrumvoting_database_nginx
    image: nginx:stable-alpine
    env_file:
      - .env.local
    ports:
      - '8080:443'
    volumes:
      - ssl-certs:/etc/ssl/certs
      - ./:/var/www/scrumvoting
      - ./.docker/scrumvoting/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - scrumvoting_app
      - scrumvoting_database

volumes:
  ssl-certs: